spring.data.mongodb.uri=mongodb+srv://satyamvatsk_db_user:FKqXT7NtOllKPq4S@cluster0.njxtjfp.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true